'use client'
import { useTheme } from '@/contexts/ThemeContext';
import Link from 'next/link';

export default function WritingIndex() {
  const { darkMode } = useTheme();

  return (
    <div className={`min-h-screen ${darkMode ? 'bg-[#1A1A1A]' : 'bg-white'}`}>
      <div className="max-w-4xl mx-auto px-6 py-12">
        <h1 className={`text-4xl font-bold mb-8 ${
          darkMode ? 'text-white' : 'text-black'
        }`}>
          Notes on Design
        </h1>
        <div className={`${darkMode ? 'text-gray-300' : 'text-gray-700'} space-y-8`}>
          <p className="text-lg">
            Thoughts, insights, and reflections on design, development, and the intersection of technology and human experience. Just kidding, I'm not that profound, this was just generated by the AI...
          </p>
          
          <div className="space-y-6">
            <Link 
              href="/writing/vibe-coding-my-portfolio"
              className={`block p-6 rounded-lg transition-all hover:scale-[1.02] ${
                darkMode 
                  ? 'bg-[#2A2A2A] hover:bg-[#3A3A3A]' 
                  : 'bg-gray-50 hover:bg-gray-100'
              }`}
            >
              <h2 className={`text-2xl font-semibold mb-2 ${
                darkMode ? 'text-white' : 'text-black'
              }`}>
                Vibe Coding My Portfolio
              </h2>
              <p className={`${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
              How I Built (and Broke) My Site So You Don't Have To
              </p>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
} 